### ISSUE TITLE
Pass cross account role

### ISSUE THREAD

**Issue by Dicondur** [awslabs/aws-config-rdklib#29]
Please add feature for Rules Lambda to assume cross account roles.
Please point to docs if this can be possible with current release. Thnx!

**Comment by bmorrissirromb** [comment]
https://aws.amazon.com/blogs/mt/deploying-custom-aws-config-rules-in-an-aws-organization-environment/

I think this can be done in the current release. The above blog post is one of my favorites and details it well. However, instead of non-rdklib RDK's `ASSUME_ROLE_MODE` being hardcoded to `True` in the Python rule code, `rdklib` reads it from `parameters.json`'s `AssumeRoleMode` InputParameter.

TLDR: Config rule runs in member account, invokes the Lambda in the Audit account (allowed via a resource policy on the Lambda allowing the Config service principal), Lambda then uses the invocation context to assume an execution role in the original member account. Logs and Config rule results are stored in the member account.

I'll close this issue based on the above documentation, but feel free to re-open if this doesn't meet your need.
